server:
  #  address: localhost
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/giggyrank
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
